import { Trans, useTranslation } from 'react-i18next'
import './App.css'
import Header, { HEADER_MODE } from './Header'
import ImagedSection from './Components/ImagedSection'

function App() {
    const { t } = useTranslation()

    return (
        <>
            <Header mode={HEADER_MODE.OnTop} />
            <Header mode={HEADER_MODE.Other} />
            <ImagedSection src=''>
                {/* TODO: add source */}
                <h1>
                    <Trans i18nKey='section[0].head'>
                        3D Model
                        <br />
                        generated with AI
                    </Trans>
                </h1>
                <p>
                    <Trans i18nKey='section[0].body'>
                        Experience 3D model
                        <br />
                        automatically generated by AI
                        <br />
                        and easy-to-use editing.
                    </Trans>
                </p>
                <button>{t('getStarted')}</button>
            </ImagedSection>
        </>
    )
}

export default App
